# Generated by Django 3.0.4 on 2020-04-17 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=15)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='diversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20, null=True)),
                ('dest', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('diver', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='p_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu_name', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('e_mail', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('u_name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(default='000', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('f_name', models.CharField(max_length=10, null=True)),
                ('l_name', models.CharField(max_length=10, null=True)),
                ('licence_no', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('e_mail', models.EmailField(max_length=254, null=True)),
                ('p_no', models.IntegerField(null=True)),
            ],
        ),
    ]
