# Generated by Django 3.0.4 on 2020-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devta', '0002_media_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=25)),
                ('u_name', models.CharField(max_length=35)),
                ('issue', models.CharField(max_length=100)),
            ],
        ),
    ]
