# Generated by Django 3.0.4 on 2020-04-22 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devta', '0004_auto_20200421_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
